[project]
name = "topic-shift"
version = "0.1.0"
description = "This package extract topics and contents from lecture slides"
authors = [{ name = "Linus Bierhoff", email = "linus.bierhoff@icloud.com" }]
requires-python = ">=3.11,<3.13"
dependencies = [
    "fastapi[standard] (>=0.120.2,<0.121.0)",
    "pydantic (>=2.12.3,<3.0.0)",
    "loguru (>=0.7.3,<0.8.0)",
    "requests (>=2.31.0,<3.0.0)",
    "docling (>=2.84.0,<3.0.0)",
    "haystack-ai (>=2.27.0,<3.0.0)",
    "docling-haystack (>=0.1.1,<0.2.0)",
    "networkx (>=3.6.1,<4.0.0)",
    "pyvis (>=0.3.2,<0.4.0)",
    "scikit-learn (>=1.8.0,<2.0.0)",
    "tinydb (>=4.8.2,<5.0.0)",
    "click (>=8.3.2,<9.0.0)",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
    "ruff>=0.9.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.ruff]
line-length = 88
indent-width = 4
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I", "N", "UP", "B", "A", "C4", "SIM", "ARG", "PTH", "RET"]
ignore = ["E501", "N815", "N803"]
fixable = ["ALL"]

[tool.ruff.lint.isort]
known-first-party = ["topic_shift"]
